export const questions = [
  {
    correct_option: "option3",
    option1: "தேம்",
    option2: "தேர்",
    option3: "தேன்",
    option4: "தேள்",
    image_fname: "https://academy.karky.in/game/datas/picture/W018.png",
    complexity: "Easy",
  },
  {
    correct_option: "option1",
    option1: "வீடு",
    option2: "வாடு",
    option3: "வேல்",
    option4: "வேடு",
    image_fname: "https://academy.karky.in/game/datas/picture/W012.png",
    complexity: "Easy",
  },
  {
    correct_option: "option3",
    option1: "பட்டி",
    option2: "பற்று",
    option3: "பட்டம்",
    option4: "பட்டை",
    image_fname: "https://academy.karky.in/game/datas/picture/W002.png",
    complexity: "Easy",
  },
  {
    correct_option: "option2",
    option1: "அறவன்",
    option2: "அரசன்",
    option3: "அரசம்",
    option4: "அரகன்",
    image_fname: "https://academy.karky.in/game/datas/picture/W008.png",
    complexity: "Mid",
  },
  {
    correct_option: "option2",
    option1: "யாமை",
    option2: "யானை",
    option3: "யாளை",
    option4: "யாழை",
    image_fname: "https://academy.karky.in/game/datas/picture/W015.png",
    complexity: "Mid",
  },
  {
    correct_option: "option1",
    option1: "குரங்கு",
    option2: "குளங்கு",
    option3: "குலங்கு",
    option4: "குறங்கு",
    image_fname: "https://academy.karky.in/game/datas/picture/W020.png",
    complexity: "Mid",
  },
  {
    correct_option: "option4",
    option1: "விமானத்தளம்",
    option2: "விமானப்பாதை",
    option3: "விமானக்கூடம்",
    option4: "விமானநிலையம்",
    image_fname: "https://academy.karky.in/game/datas/picture/W024.png",
    complexity: "Hard",
  },
  {
    correct_option: "option4",
    option1: "தொலைவாக்கி",
    option2: "தொலைப்பேசி",
    option3: "தொலைநோக்கி",
    option4: "தொலைக்காட்சி",
    image_fname: "https://academy.karky.in/game/datas/picture/W023.png",
    complexity: "Hard",
  },
  {
    correct_option: "option4",
    option1: "பள்ளிக்குளம்",
    option2: "பள்ளிக்கோடு",
    option3: "பள்ளிக்காடு",
    option4: "பள்ளிக்கூடம்",
    image_fname: "https://academy.karky.in/game/datas/picture/W021.png",
    complexity: "Hard",
  },
];
